# Generated by Django 5.1.2 on 2024-10-25 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+989xxxxxxxxx' or '09xxxxxxxxx'.",
                        regex="^(\\+98|0)?9\\d{9}$",
                    )
                ],
            ),
        ),
    ]
