# Generated by Django 5.1.2 on 2024-10-27 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0002_remove_cafe_owner_cafe_number_of_tables"),
        ("customer", "0003_customer_table_number_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.AddField(
            model_name="customer",
            name="cafe",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="cafe.cafe",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="table_number",
            field=models.BigIntegerField(),
        ),
    ]
