# Generated by Django 5.1.2 on 2024-10-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_remove_customer_user_customer_cafe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="table_number",
            field=models.PositiveIntegerField(),
        ),
    ]
