# Generated by Django 5.1.2 on 2024-10-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_alter_customer_table_number"),
        ("customer", "0005_cafe_alter_customer_cafe"),
    ]

    operations = []
