# Generated by Django 5.1.2 on 2024-10-29 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0002_remove_cafe_owner_cafe_number_of_tables"),
        ("customer", "0006_merge_20241029_1146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cafe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cafe.cafe",
            ),
        ),
        migrations.DeleteModel(
            name="Cafe",
        ),
    ]
