# Generated by Django 5.1.2 on 2024-11-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_alter_customer_cafe_delete_cafe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
