# Generated by Django 5.1.2 on 2024-10-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="is_staff",
        ),
        migrations.AlterField(
            model_name="staff",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[("M", "Manager"), ("S", "Staff")], max_length=1
            ),
        ),
    ]
