# Generated by Django 5.1.2 on 2024-10-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_alter_staff_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="_is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
