# Generated by Django 5.1.2 on 2024-10-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_remove_staff_is_staff_alter_staff_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
