# Generated by Django 5.1.2 on 2024-10-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_staff__is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="_is_admin",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="staff",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "manager"),
                    ("waiter", "waiter"),
                    ("chef", "chef"),
                    ("assistant cook", "assistant cook"),
                    ("dish washer", "dish washer"),
                    ("services", "services"),
                ],
                max_length=40,
            ),
        ),
    ]
