# Generated by Django 5.1.2 on 2024-10-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_remove_staff__is_admin_remove_staff_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
