# Generated by Django 5.1.2 on 2024-10-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_alter_staff_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("waiter", "Waiter"),
                    ("chef", "Chef"),
                    ("assistant cook", "Assistant Cook"),
                    ("dish washer", "Dish Washer"),
                    ("services", "Services"),
                ],
                max_length=40,
            ),
        ),
    ]
