# Generated by Django 5.1.2 on 2024-10-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cafe",
            name="owner",
        ),
        migrations.AddField(
            model_name="cafe",
            name="number_of_tables",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
