# Generated by Django 5.1.2 on 2024-11-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0002_remove_cafe_owner_cafe_number_of_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafe",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
