# Generated by Django 5.1.2 on 2024-11-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0004_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cafe",
            name="number_of_tables",
        ),
    ]
