# Generated by Django 5.1.2 on 2024-11-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0005_remove_cafe_number_of_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="status",
            field=models.CharField(
                choices=[("A", "available"), ("U", "unavailable")],
                default="available",
                max_length=20,
            ),
        ),
    ]
