# Generated by Django 5.1.2 on 2024-10-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart_items",
            field=models.ManyToManyField(to="order.cartitem"),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
