# Generated by Django 5.1.2 on 2024-10-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_remove_cartitem_cart_remove_cartitem_menu_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="table_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                    ("Canceled", "Canceled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
