# Generated by Django 5.1.2 on 2024-10-22 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_customer_phone_number"),
        ("order", "0004_remove_cartitem_cart_orderhistory_orderitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart_items",
        ),
        migrations.AddField(
            model_name="orderhistory",
            name="guest_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer.customer",
            ),
        ),
        migrations.AlterField(
            model_name="orderhistory",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
            ),
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
