# Generated by Django 5.1.2 on 2024-10-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_remove_order_cart_items_orderhistory_guest_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
