# Generated by Django 5.1.2 on 2024-11-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_order_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderHistory",
        ),
    ]
