# Generated by Django 5.1.2 on 2024-10-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_orderitem_subtotal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
